### ISSUE TITLE
Tracking and snapshot improvements

### ISSUE THREAD

**Issue by Vaurkhorov** [Vaurkhorov/kifi#5]
TODO:
- [x] kifi needs to look recursively within subfolders while caching file lists.
- [x] previews - similar to 'git status'
- [x] changes need to be compared, perhaps the meta file will store the most recent snapshot, which will then be compared to current files
- [ ] add option to 'stage' changes
- [x] #24
- [ ] #29
- [x] #30
